### ISSUE TITLE
Reconstruction time

### ISSUE THREAD

**Issue by nicolasugrinovic** [xiexh20/CHORE#1]
Hi, 

Thanks for releasing this code. It is truly a very exciting work! 

I was wondering **how much time it takes** on average to make one estimation with your method? I run some examples on my PC, it takes me around **03:30 minutes** for one image reconstruction. 

Is this the same time it takes you? Any advice on how to run the optimization faster?

Thanks in advance : )

**Comment by xiexh20** [comment]
Hello,

Thanks for your interest. 
The running time on my side is similar to 2~3min. To speed up, you can run multiple examples in parallel by using batch size>1.  I tried batch size=32 with 48GB memory. 
The memory bottleneck is the point generation process, see [this line](https://github.com/xiexh20/CHORE/blob/a52db9bc0e58e5da4cb0e0c58be497dc8ada613a/recon/recon_fit_behave.py#L46). But the generation is pretty fast. So if you want to speed up even further., you can save the point generation results and run joint optimization with an even larger batch size. 

Best,

**Comment by nicolasugrinovic** [comment]
Great, thank you very much for the insight! I will try you suggestions
