### ISSUE TITLE
Which SMPL+H Body Model to use & where to extract?

### ISSUE THREAD

**Issue by FS93** [xiexh20/CHORE#4]
In your installation guide it says

> We use the SMPL-H body model, please prepare it from the [official website](https://mano.is.tue.mpg.de/) and modify SMPL_MODEL_ROOT in PATHS.yml accordingly.

However, in the Download section there are multiple archives to download (Models & Code, Extended SMPL+H Model, Scans, Registrations...). 

1. **Which one do I have to use?**
2. **Does it matter where I extract the archive?**
3. **Furthermore, which directory do I have to enter in the SMPL_MODEL_ROOT variable** (I guess the root directory of the archive)?

Thank you for your support!

**Comment by xiexh20** [comment]
hello, thanks for your interest!
1. You can use the SMPLH v1.2 model.
2&3. You need to specify the model path here: https://github.com/xiexh20/CHORE/blob/main/PATHS.yml it is the root directory of the archive
