### ISSUE TITLE
How to test BEHAVE test set?

### ISSUE THREAD

**Issue by kaenkogashi** [xiexh20/CHORE#5]
@xiexh20  Thank you very much for your great work!

The python script don't work so that I can't test CHORE on BEHAVE test set as follows.

From your github,
>Test on BEHAVE test set
>After downloading the pretrained model, you can test one sequence from behave data with:

>python recon/recon_fit_behave.py chore-release --save_name chore-release -s [path to one sequence]

I just try 
python recon/recon_fit_behave.py chore-release --save_name chore-release -s /data2/BEHAVE_data/test/Date03_Sub03_backpack_back (This is my folder pass)

Then I have next results. Would you show me how to test CHORE on BEHAVE test set? Thank you very much!
>configs loaded from config/chore-release.json
In total 0 test examples
>Loaded checkpoint from: /home/work/CHORE/recon/../experiments/chore-release/checkpoints/checkpoint_38h:1m:33s_136893.18501019478.tar
>Date03_Sub03_backpack_back: : 0it [00:00, ?it/s]
>all done

**Comment by xiexh20** [comment]
Hi, 

The image paths are found by [this function](https://github.com/xiexh20/CHORE/blob/edd6d35debd7b6d89c0666d782e8f191f2bd07c2/data/data_paths.py#L38).

If no image files are found, maybe you should set `check_occlusion` to `False` in [this line](https://github.com/xiexh20/CHORE/blob/main/recon/recon_fit_behave.py#L80). I have set this to False by default in the newest commit.

**Comment by kaenkogashi** [comment]
Thank you very much for your reply!
