### ISSUE TITLE
Doubts about training

### ISSUE THREAD

**Issue by Vivien888** [xiexh20/CHORE#8]
Hello, I try to train on the behave dataset, but I always get an error "cuda out of memory". I would like to ask what GPU you used for training? In addition, I would like to ask that you mentioned that you also used COCO and NTU-RGBD datasets for training in your paper. Can you provide relevant training codes and NTU-RGBD datasets?

**Comment by xiexh20** [comment]
Hi, 

We used 3 RTX8000 GPUs, each with 48GB memory to train the model. If you get the out of memory error, you can try to reduce the batch size. 

No, we did not train on COCO and NTU-RGBD datasets as there are no 3D GT available for training. We only tested our method pretrained on BEHAVE on these datasets.

**Comment by Vivien888** [comment]
> 

Thank you for your reply. I would also like to ask how can I test a single RGB image now. Do I have to generate "color.json " "mocap.[json|ply]" "_mask.jpg " files first and then input them with the RGB picture? If yes, how can I obtain the mask images? Looking forward to your reply.

**Comment by xiexh20** [comment]
Hi,

Yes, you need to prepare these files for your own input images. 

To generate masks, you can use interactive segmentation such as [this ritm](https://github.com/SamsungLabs/ritm_interactive_segmentation), and for video you can also use video segmentation such as [MiVOS](https://github.com/hkchengrex/MiVOS).

The `color.json` file stores openpose predictions, you can simply run [openpose](https://github.com/CMU-Perceptual-Computing-Lab/openpose) on your images and save the results following the same format. 

The `mocap.json|ply` stores the SMPL  model parameters and SMPL meshes estimated by [FrankMocap](https://github.com/facebookresearch/frankmocap).


Hope that helps.
